global_context: &global_context
  context:
    - org-global
global_remote_docker: &global_remote_docker
  version: 19.03.13
global_dockerhub_auth: &global_dockerhub_auth
  auth:
    username: $GLOBAL_DOCKERHUB_USERNAME
    password: $GLOBAL_DOCKERHUB_PASSWORD

defaults: &defaults
  working_directory: /circleci
  docker:
    - image: docker:17.06.0-ce-git
      <<: *global_dockerhub_auth

version: 2

jobs:

  10i_build_image:
    parallelism: 4
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t $(./image) .
          no_output_timeout: 300m 

  10j_test_image:
    parallelism: 4
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t $(./image) .
          no_output_timeout: 300m 
            
            
  10k_push_image:
    parallelism: 4
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t $(./image) .
          no_output_timeout: 300m 
            
            
  10l_build_image:
    parallelism: 4
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t $(./image) .
          no_output_timeout: 300m 

  10m_test_image:
    parallelism: 4
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t $(./image) .
          no_output_timeout: 300m 

workflows:
  version: 2
  test:
    jobs:
      - 10i_build_image
      - 10j_test_image
      - 10k_push_image
      - 10l_build_image
      - 10m_test_image
